/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LibraryContentIdRouteImport } from './routes/library.$contentId'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as CommunityNewRouteImport } from './routes/community.new'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminNewsletterRouteImport } from './routes/admin.newsletter'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminContentIndexRouteImport } from './routes/admin.content.index'
import { Route as LibraryCategorySlugRouteImport } from './routes/library.category.$slug'
import { Route as CommunityTopicIdRouteImport } from './routes/community.topic.$id'
import { Route as AdminContentNewRouteImport } from './routes/admin.content.new'
import { Route as AdminContentIdEditRouteImport } from './routes/admin.content.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LibraryContentIdRoute = LibraryContentIdRouteImport.update({
  id: '/library/$contentId',
  path: '/library/$contentId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityNewRoute = CommunityNewRouteImport.update({
  id: '/community/new',
  path: '/community/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentIndexRoute = AdminContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => AdminRoute,
} as any)
const LibraryCategorySlugRoute = LibraryCategorySlugRouteImport.update({
  id: '/library/category/$slug',
  path: '/library/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityTopicIdRoute = CommunityTopicIdRouteImport.update({
  id: '/community/topic/$id',
  path: '/community/topic/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentNewRoute = AdminContentNewRouteImport.update({
  id: '/content/new',
  path: '/content/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentIdEditRoute = AdminContentIdEditRouteImport.update({
  id: '/content/$id/edit',
  path: '/content/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/community/new': typeof CommunityNewRoute
  '/events/$id': typeof EventsIdRoute
  '/library/$contentId': typeof LibraryContentIdRoute
  '/admin/': typeof AdminIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/events/': typeof EventsIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/admin/content/new': typeof AdminContentNewRoute
  '/community/topic/$id': typeof CommunityTopicIdRoute
  '/library/category/$slug': typeof LibraryCategorySlugRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/content/$id/edit': typeof AdminContentIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/community/new': typeof CommunityNewRoute
  '/events/$id': typeof EventsIdRoute
  '/library/$contentId': typeof LibraryContentIdRoute
  '/admin': typeof AdminIndexRoute
  '/community': typeof CommunityIndexRoute
  '/events': typeof EventsIndexRoute
  '/library': typeof LibraryIndexRoute
  '/admin/content/new': typeof AdminContentNewRoute
  '/community/topic/$id': typeof CommunityTopicIdRoute
  '/library/category/$slug': typeof LibraryCategorySlugRoute
  '/admin/content': typeof AdminContentIndexRoute
  '/admin/content/$id/edit': typeof AdminContentIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/community/new': typeof CommunityNewRoute
  '/events/$id': typeof EventsIdRoute
  '/library/$contentId': typeof LibraryContentIdRoute
  '/admin/': typeof AdminIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/events/': typeof EventsIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/admin/content/new': typeof AdminContentNewRoute
  '/community/topic/$id': typeof CommunityTopicIdRoute
  '/library/category/$slug': typeof LibraryCategorySlugRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/content/$id/edit': typeof AdminContentIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/newsletter'
    | '/profile'
    | '/signup'
    | '/admin/categories'
    | '/admin/events'
    | '/admin/newsletter'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/callback'
    | '/community/new'
    | '/events/$id'
    | '/library/$contentId'
    | '/admin/'
    | '/community/'
    | '/events/'
    | '/library/'
    | '/admin/content/new'
    | '/community/topic/$id'
    | '/library/category/$slug'
    | '/admin/content/'
    | '/admin/content/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/newsletter'
    | '/profile'
    | '/signup'
    | '/admin/categories'
    | '/admin/events'
    | '/admin/newsletter'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/callback'
    | '/community/new'
    | '/events/$id'
    | '/library/$contentId'
    | '/admin'
    | '/community'
    | '/events'
    | '/library'
    | '/admin/content/new'
    | '/community/topic/$id'
    | '/library/category/$slug'
    | '/admin/content'
    | '/admin/content/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/newsletter'
    | '/profile'
    | '/signup'
    | '/admin/categories'
    | '/admin/events'
    | '/admin/newsletter'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/callback'
    | '/community/new'
    | '/events/$id'
    | '/library/$contentId'
    | '/admin/'
    | '/community/'
    | '/events/'
    | '/library/'
    | '/admin/content/new'
    | '/community/topic/$id'
    | '/library/category/$slug'
    | '/admin/content/'
    | '/admin/content/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NewsletterRoute: typeof NewsletterRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CommunityNewRoute: typeof CommunityNewRoute
  EventsIdRoute: typeof EventsIdRoute
  LibraryContentIdRoute: typeof LibraryContentIdRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  CommunityTopicIdRoute: typeof CommunityTopicIdRoute
  LibraryCategorySlugRoute: typeof LibraryCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/library/$contentId': {
      id: '/library/$contentId'
      path: '/library/$contentId'
      fullPath: '/library/$contentId'
      preLoaderRoute: typeof LibraryContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/new': {
      id: '/community/new'
      path: '/community/new'
      fullPath: '/community/new'
      preLoaderRoute: typeof CommunityNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/': {
      id: '/admin/content/'
      path: '/content'
      fullPath: '/admin/content/'
      preLoaderRoute: typeof AdminContentIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/library/category/$slug': {
      id: '/library/category/$slug'
      path: '/library/category/$slug'
      fullPath: '/library/category/$slug'
      preLoaderRoute: typeof LibraryCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/topic/$id': {
      id: '/community/topic/$id'
      path: '/community/topic/$id'
      fullPath: '/community/topic/$id'
      preLoaderRoute: typeof CommunityTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/new': {
      id: '/admin/content/new'
      path: '/content/new'
      fullPath: '/admin/content/new'
      preLoaderRoute: typeof AdminContentNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/$id/edit': {
      id: '/admin/content/$id/edit'
      path: '/content/$id/edit'
      fullPath: '/admin/content/$id/edit'
      preLoaderRoute: typeof AdminContentIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminContentNewRoute: typeof AdminContentNewRoute
  AdminContentIndexRoute: typeof AdminContentIndexRoute
  AdminContentIdEditRoute: typeof AdminContentIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminContentNewRoute: AdminContentNewRoute,
  AdminContentIndexRoute: AdminContentIndexRoute,
  AdminContentIdEditRoute: AdminContentIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NewsletterRoute: NewsletterRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CommunityNewRoute: CommunityNewRoute,
  EventsIdRoute: EventsIdRoute,
  LibraryContentIdRoute: LibraryContentIdRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  CommunityTopicIdRoute: CommunityTopicIdRoute,
  LibraryCategorySlugRoute: LibraryCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
